# AUTO-GENERATED by scripts/generate_record_layers.py
# DO NOT EDIT MANUALLY
# Generated: 2026-02-22 12:21:25
# Source: msd-transfer C++ records
# Ticket: 0062_pybind_codegen_from_boost_describe
# Updated: 2026-02-22 — Ticket: 0075a_unified_constraint_data_structure
#   Added UnifiedContactConstraint; removed ContactConstraint/FrictionConstraint

"""
Leaf Pydantic models generated from msd-transfer C++ record definitions.

These models are structurally equivalent to their C++ counterparts and provide
deterministic linkage via Maps-to: annotations for the 0061 mapping indexer.

Hand-written composite models (FrameData, BodyState, etc.) should import from
this module rather than redefining leaf models.
"""

from pydantic import BaseModel


class Vec3(BaseModel):
    """Generated from AccelerationRecord. Maps-to: AccelerationRecord"""

    x: float
    y: float
    z: float

class ContactPoint(BaseModel):
    """Generated from ContactPointRecord. Maps-to: ContactPointRecord"""

    point_a: Vec3
    point_b: Vec3
    depth: float

class EnergyPoint(BaseModel):
    """Generated from EnergyRecord. Maps-to: EnergyRecord"""

    body_id: int
    linear_ke: float
    rotational_ke: float
    potential_e: float
    total_e: float
    frame_id: int

class Quaternion(BaseModel):
    """Generated from QuaternionDRecord. Maps-to: QuaternionDRecord"""

    w: float
    x: float
    y: float
    z: float

class SolverDiagnostics(BaseModel):
    """Generated from SolverDiagnosticRecord. Maps-to: SolverDiagnosticRecord"""

    iterations: int
    residual: float
    converged: int
    num_constraints: int
    num_contacts: int
    frame_id: int

class SystemEnergyPoint(BaseModel):
    """Generated from SystemEnergyRecord. Maps-to: SystemEnergyRecord"""

    total_linear_ke: float
    total_rotational_ke: float
    total_potential_e: float
    total_system_e: float
    delta_e: float
    energy_injection: int
    collision_active: int
    frame_id: int

class UnifiedContactConstraint(BaseModel):
    """Generated from UnifiedContactConstraintRecord.
    Maps-to: UnifiedContactConstraintRecord.
    Ticket: 0075a_unified_constraint_data_structure.
    Supersedes ContactConstraint and FrictionConstraint leaf models.
    For frictionless contacts, tangent1/tangent2 are zero vectors and
    friction_coefficient/tangent1_lambda/tangent2_lambda are NaN."""

    body_a_id: int
    body_b_id: int
    normal: Vec3
    lever_arm_a: Vec3
    lever_arm_b: Vec3
    penetration_depth: float
    restitution: float
    pre_impact_rel_vel_normal: float
    tangent1: Vec3
    tangent2: Vec3
    friction_coefficient: float
    normal_lambda: float
    tangent1_lambda: float
    tangent2_lambda: float
    frame_id: int
