# AUTO-GENERATED by scripts/generate_record_layers.py
# DO NOT EDIT MANUALLY
# Generated: 2026-02-19 12:48:45
# Source: msd-transfer C++ records
# Ticket: 0062_pybind_codegen_from_boost_describe

"""
Leaf Pydantic models generated from msd-transfer C++ record definitions.

These models are structurally equivalent to their C++ counterparts and provide
deterministic linkage via Maps-to: annotations for the 0061 mapping indexer.

Hand-written composite models (FrameData, BodyState, etc.) should import from
this module rather than redefining leaf models.
"""

from pydantic import BaseModel


class Vec3(BaseModel):
    """Generated from AccelerationRecord. Maps-to: AccelerationRecord"""

    x: float
    y: float
    z: float

class ContactPoint(BaseModel):
    """Generated from ContactPointRecord. Maps-to: ContactPointRecord"""

    point_a: Vec3
    point_b: Vec3
    depth: float

class EnergyPoint(BaseModel):
    """Generated from EnergyRecord. Maps-to: EnergyRecord"""

    body_id: int
    linear_ke: float
    rotational_ke: float
    potential_e: float
    total_e: float
    frame_id: int

class Quaternion(BaseModel):
    """Generated from QuaternionDRecord. Maps-to: QuaternionDRecord"""

    w: float
    x: float
    y: float
    z: float

class SolverDiagnostics(BaseModel):
    """Generated from SolverDiagnosticRecord. Maps-to: SolverDiagnosticRecord"""

    iterations: int
    residual: float
    converged: int
    num_constraints: int
    num_contacts: int
    frame_id: int

class SystemEnergyPoint(BaseModel):
    """Generated from SystemEnergyRecord. Maps-to: SystemEnergyRecord"""

    total_linear_ke: float
    total_rotational_ke: float
    total_potential_e: float
    total_system_e: float
    delta_e: float
    energy_injection: int
    collision_active: int
    frame_id: int
